name: Bug Report
description: Report a bug or issue with the project
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please check all boxes before submitting
      options:
        - label: I have searched existing issues and found no duplicates
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using a supported version (Node.js 22+)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: "The bug occurs when..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. ...
        2. ...
        3. ...
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead
      placeholder: "The application should..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens
      placeholder: "Instead, the application..."
    validations:
      required: true

  - type: dropdown
    id: environment-os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: environment-node
    attributes:
      label: Node.js Version
      placeholder: "22.x"
    validations:
      required: true

  - type: input
    id: environment-npm
    attributes:
      label: npm Version
      placeholder: "10.x"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Include any relevant error messages or logs
      placeholder: |
        ```
        Error: ...
        ```
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information that might help
      placeholder: "Screenshots, code snippets, or other context..."
