name: Feature Request
description: Suggest an idea or feature for the project
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement!

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please check all boxes before submitting
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature is not already implemented
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the feature
      placeholder: "I would like to..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful?
      placeholder: "This would be helpful because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: "The implementation could..."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've thought about
      placeholder: "Other options include..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, code snippets, or other information
      placeholder: "Examples or use cases..."
